### PR TITLE
added curriculum

### PR DESCRIPTION
**Pull request by milistisia2**
used the online editor because there's something messed up with my local clone and i don't have the time to figure it out atm

### CODE REVIEW

**Comment by milistisia2** [comment]
also added teamprop

**Comment by Nolski** [comment]
please pull from upstream

**Comment by decause** [comment]
@milistisia2 be sure to <code>git pull</code> and merge from upstream.

**Comment by Nolski** [comment]
@milistisia2 we would like to get this merged so please `git pull` from upstream

**Comment by milistisia2** [comment]
I couldn't figure out how to fix my repository, so I just decided to remake it and add in my changes again. I opened a new pull request

**Comment by liam-middlebrook** [comment]
In the future feel free to tag someone and ask for help.

**Pull request closed without merging**
