### PR TITLE
Switch to use new 3-arg gravatar function

### PR DESCRIPTION
**Pull request by ryansb**

### CODE REVIEW

**Comment by liam-middlebrook** [comment]
@decause you need to merge this PR before the next time you push to production. I currently have hotfixed it in production by merging this patch in.

@Nolski since you have Collaborator status if you see this before @decause you should merge this in.

**Comment by Nolski** [comment]
:grapes:

**Comment by liam-middlebrook** [comment]
But why grapes!?

**Comment by ryansb** [comment]
:walking: :grapes: :whale:

**Pull request merged**
