### PR TITLE
Added hackathons, upstreams, and final infomation to jal5313.yaml

### PR DESCRIPTION
**Pull request by jal5313**

### CODE REVIEW

**Comment by liam-middlebrook** [comment]
Your `upstream<n>` keys appear to be labeled `uprstream<n>` :grey_exclamation: 

You also have 2 blank lines at the end of your file :page_with_curl:

**Comment by jal5313** [comment]
Good catch. Should be fixed. Thanks!

**Comment by liam-middlebrook** [comment]
lgtm :+1:

**Comment by decause** [comment]
:checkered_flag:

**Pull request merged**
