### PR TITLE
Issue #126 - Guest Lecture from RyanSB

### PR DESCRIPTION
**Pull request by Kaffys**
Fixed Issue #126 - Guest Lecture from RyanSB on the Syllabus

### CODE REVIEW

**Comment by Nolski** [comment]
LGTM :+1:

**Comment by ryansb** [comment]
What, am I not special?

**Comment by decause** [comment]
:racehorse:

**Comment by ryansb** [comment]
More like :late horse:

**Comment by liam-middlebrook** [comment]
:clock11: :horse_racing: :clock1130: :clock12: :clock1230: :horse: :crying_cat_face: :glue:

**Pull request merged**
