### PR TITLE
Added a bunch of stuff; Education team prop

### PR DESCRIPTION
**Pull request by direkitteh**
"Mini Game Mayhem"

direkitteh
milistisia2
NumbuhFour
holtr94

note: some of the new links go to incomplete assignments

### CODE REVIEW

**Comment by Nolski** [comment]
Please pull from upstream (and then push) and this should be good to merge.

**Comment by decause** [comment]
@direkitteh be sure to <code>git pull</code> and merge from upstream.

**Comment by direkitteh** [comment]
The thing works!

**Comment by Nolski** [comment]
:rocket:

**Pull request merged**
