### PR TITLE
Add commarch

### PR DESCRIPTION
**Pull request by Red-Two**
preso and report

### CODE REVIEW

**Comment by Nolski** [comment]
@Red-Two  Could you add the key name: to the yaml file? It's now required to have a valid ofCourse yaml key. Feel free to put your normal name, handle, or whatever you feel is appropriate.

**Comment by Red-Two** [comment]
@Nolski it is in the file... Line 6:  "name: William Russell"

**Comment by Nolski** [comment]
Right. My bad. Pull from upstream (and then push) and you should be good to merge.

**Comment by decause** [comment]
@Red-Two be sure to <code>git pull</code> and merge from upstream.

**Pull request closed without merging**
