### PR TITLE
Added commarchpreso to yaml

### PR DESCRIPTION
**Pull request by NumbuhFour**

### CODE REVIEW

**Comment by Nolski** [comment]
@fad4470 Could you add the key `name:` to the yaml file? It's now required to have a valid ofCourse yaml key. Feel free to put your normal name, handle, or whatever you feel is appropriate.

**Comment by Nolski** [comment]
Looks like you're a bit behind `decause/hfoss`. Could you pull from upstream and push your code to update this PR? Then you should be good to merge.

**Comment by decause** [comment]
@fad4470 be sure to <code>git pull</code> and merge from upstream.

**Comment by Nolski** [comment]
LGTM :rocket:

**Comment by decause** [comment]
:mobile_phone_off: :game_die:

**Pull request merged**
