### PR TITLE
update yaml file

### PR DESCRIPTION
**Pull request by Red-Two**

### CODE REVIEW

**Comment by Nolski** [comment]
pls pull and update

**Comment by liam-middlebrook** [comment]
@Red-Two are you having any problems with this process? Feel free to ask someone in IRC or ask me before/during/after class this week.

**Comment by decause** [comment]
@Red-Two be sure to <code>git pull</code> from upstream and merge.

**Comment by decause** [comment]
@Red-Two ping! :zap:

**Comment by decause** [comment]
@Red-Two You _must_ <code>git pull</code> from <code>decause/master</code> and merge upstream into your repo before I can accept your pull-request. Please do this ASAP.

**Pull request closed without merging**
