### PR TITLE
TeamProp0 - CommArch

### PR DESCRIPTION
**Pull request by fortnight**
maybe it should be teamprop1?

### CODE REVIEW

**Comment by decause** [comment]
@fortnight yes, <code>teamprop1</code>

:wrench: and I'll :twisted_rightwards_arrows:

**Comment by Nolski** [comment]
@fortnight Could you add the key name: to the yaml file? It's now required to have a valid ofCourse yaml key. Feel free to put your normal name, handle, or whatever you feel is appropriate.

**Comment by decause** [comment]
@fortnight remove the underscores from your <code>commarch</code>entries and I'll merge.

While you are at it, maybe add a <code>name</code> field.

**Comment by liam-middlebrook** [comment]
What @decause means is [definitely add a `name` field](https://travis-ci.org/decause/hfoss/builds/54650534)

**Comment by decause** [comment]
@fortnight see above comments (particularly about adding names and removing underscores)

**Comment by fortnight** [comment]
:new_moon: :waxing_crescent_moon: :first_quarter_moon: :waxing_gibbous_moon: :full_moon:

**Comment by Nolski** [comment]
LGTM :+1:

**Comment by decause** [comment]
:large_orange_diamond: :palm_tree:

**Pull request merged**
