### PR TITLE
added commarch stuff to amm4108.yaml

### PR DESCRIPTION
**Pull request by Aalaizah**

### CODE REVIEW

**Comment by Nolski** [comment]
@amm4108 Could you add the key name: to the yaml file? It's now required to have a valid ofCourse yaml key. Feel free to put your normal name, handle, or whatever you feel is appropriate.

**Comment by Aalaizah** [comment]
@Nolski added :+1:

**Comment by Nolski** [comment]
LGTM. @decause  Travis is still failing because of other students but this should be good to merge.

**Comment by Nolski** [comment]
Pull from upstream (and then push) and you should be good to merge.

**Comment by decause** [comment]
@amm4108 be sure to <code>git pull</code> and merge from upstream.

**Comment by Aalaizah** [comment]
@Nolski @decause, merged from upstream

**Comment by Nolski** [comment]
:facepunch:

**Pull request merged**
