### PR TITLE
added nolski's yaml

### PR DESCRIPTION
**Pull request by Nolski**

### CODE REVIEW

**Comment by Nolski** [comment]
@liam-middlebrook pls #shipit

**Comment by liam-middlebrook** [comment]
Nope, this will break the website.

```
Validating ofCourse Participant YAML Files
.F
======================================================================
FAIL: test_student_yaml (ofcourse.tests.test_yaml.TestAllYaml)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/liam/.virtualenvs/ofcourse/lib/python2.7/site-packages/ofcourse/tests/test_yaml.py", line 60, in test_student_yaml
    self.fail(out)
AssertionError: File: /home/liam/repos/hfoss/people/2015/spring/nolski.yaml Key: hw ['must be an instance of dict or its subclasses']



----------------------------------------------------------------------
Ran 2 tests in 0.129s

FAILED (failures=1)
```

**Comment by Nolski** [comment]
boo
how do you ofcourse validate?

**Comment by Nolski** [comment]
lemme guess... `ofcourse validate`

**Comment by liam-middlebrook** [comment]
`ofcourse validate`

**Comment by Nolski** [comment]
@liam-middlebrook pls shipit

**Comment by liam-middlebrook** [comment]
lgtm :+1:

**Comment by liam-middlebrook** [comment]
:boat: :it:

**Pull request merged**
