### PR TITLE
Added commarchreport and commarchpreso to jal5313.yaml

### PR DESCRIPTION
**Pull request by jal5313**

### CODE REVIEW

**Comment by Nolski** [comment]
@jal5313 Could you add the key name: to the yaml file? It's now required to have a valid ofCourse yaml key. Feel free to put your normal name, handle, or whatever you feel is appropriate.

**Comment by decause** [comment]
@Nolski @msoucy dunno why this can't be merged...

**Comment by msoucy** [comment]
It's because Federcheese's YAML is missing a name tag...

**Comment by Nolski** [comment]
Pull from upstream and then push. Then you should be good to merge.

**Comment by decause** [comment]
@jal5313 be sure to <code>git pull</code> and merge from upstream.

**Comment by jal5313** [comment]
I am pretty sure that I've fixed up all the conflicts and have my fork back up to date!

**Comment by Nolski** [comment]
Yup this looks good and should be good to merge.

**Comment by decause** [comment]
:keycap_ten: :o:

**Comment by msoucy** [comment]
Ten red-ring-of-death?

**Pull request merged**
