### PR TITLE
added litreview2

### PR DESCRIPTION
**Pull request by milistisia2**

### CODE REVIEW

**Comment by liam-middlebrook** [comment]
:warning: The changes that you made would remove your `teamprop2` key!

**Comment by milistisia2** [comment]
My bad when i get back to my computer ill fix that. Thanks for letting me know

**Comment by milistisia2** [comment]
There. i have no idea what's wrong, but i managed to fix it. im using sublime to edit the text file and i just added a blank line where it thought i was deleting teamprop2, and just moved the last 2 things down a row and managed to make it happy. i dont get it really, but it's at least doing what i want now

**Comment by decause** [comment]
@milistisia2 see if you can remove that blank line in there. If not, I can manually merge, but it shouldn't be too big a deal.

**Comment by milistisia2** [comment]
im not sure what the deal was with the red line, but i just recloned my repository and it became happy so i removed it. looks like its all good now

**Comment by decause** [comment]
:star2: :star: :stars: :dizzy:

**Pull request merged**
